using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Syncfusion.WinForms.DataGrid;
using Syncfusion.WinForms.DataGrid.Events;
 
using System.Globalization;
using Syncfusion.WinForms.Input.Enums;
using Syncfusion.WinForms.DataGrid.Enums;
using Syncfusion.Data;
using Syncfusion.Windows.Forms.Grid;
using Syncfusion.WinForms.DataGridConverter;
using System.IO;
using Syncfusion.XlsIO;
using Syncfusion.Windows.Forms;

namespace PaymentBatchCapacite
{
    public partial class frmTackMyBatch : Form
    {
        PayBatchClass pb = new PayBatchClass();
      
        

        public frmTackMyBatch()
        {
            InitializeComponent();
            this.Location = new Point(20, 90);
        }

     

       
        private void ResetAll()
        {
            batchGrid.Visible = true;
            btnPrint.Enabled = true;
            
        }

       

      

        private void frmBatchAwaitingApproval_Load(object sender, EventArgs e)
        {
            ResetAll();


            DataSet ds = pb.GetBatchStatus();
            batchGrid.DataSource = ds.Tables[0];
            batchGrid.FrozenColumnCount = 8;
        }


       

       

        private void batchGrid_QueryRowStyle(object sender, QueryRowStyleEventArgs e)
        {
            if (e.RowType == RowType.DefaultRow)
            {
                if (e.RowIndex % 2 == 0)
                    e.Style.BackColor = Color.Lavender;
                else
                    e.Style.BackColor = Color.AliceBlue;
            }
        }

        private void batchGrid_DrawCell(object sender, DrawCellEventArgs e)
        {
            if (batchGrid.ShowRowHeader && e.RowIndex != 0)
            {
                if (e.ColumnIndex == 0)
                {
                    e.DisplayText = e.RowIndex.ToString();
                }

            }

            if (e.DataRow.RowType == RowType.TableSummaryRow)
            {
                double result;
                double.TryParse((e.DataRow.RowData as SummaryRecordEntry).SummaryValues[0].AggregateValues.ElementAt(0).Value.ToString(), out result);
                if (result > 10000)
                    e.Style.BackColor = Color.Beige;
                else
                    e.Style.BackColor = Color.Bisque;
            }

            if (e.DataRow.RowType == RowType.HeaderRow)
            {
                e.Style.BackColor = Color.DarkBlue;
            }


        }

        private void btnPrint_Click(object sender, EventArgs e)
        {
            var options = new ExcelExportingOptions();
            options.ExcludeColumns.Add("BatchID");
            options.ExcludeColumns.Add("Selected");
            options.ExcelVersion = ExcelVersion.Excel2013;
            var excelEngine = batchGrid.ExportToExcel(batchGrid.View, options);
            var workBook = excelEngine.Excel.Workbooks[0];

            SaveFileDialog saveFilterDialog = new SaveFileDialog
            {
                FilterIndex = 2,
                Filter = "Excel 97 to 2003 Files(*.xls)|*.xls|Excel 2007 to 2010 Files(*.xlsx)|*.xlsx|Excel 2013 File(*.xlsx)|*.xlsx"
            };

            if (saveFilterDialog.ShowDialog() == System.Windows.Forms.DialogResult.OK)
            {
                using (Stream stream = saveFilterDialog.OpenFile())
                {
                    if (saveFilterDialog.FilterIndex == 1)
                        workBook.Version = ExcelVersion.Excel97to2003;
                    else if (saveFilterDialog.FilterIndex == 2)
                        workBook.Version = ExcelVersion.Excel2010;
                    else
                        workBook.Version = ExcelVersion.Excel2013;
                    workBook.SaveAs(stream);
                }

                //Message box confirmation to view the created workbook.
                MessageBoxAdv.MessageBoxStyle = MessageBoxAdv.Style.Office2016;
                if (MessageBoxAdv.Show(this.batchGrid, "Do you want to view the workbook?", "Workbook has been created",
                                    MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.Yes)
                {

                    //Launching the Excel file using the default Application.[MS Excel Or Free ExcelViewer]
                    System.Diagnostics.Process.Start(saveFilterDialog.FileName);
                }
            }

        }

      

        private void batchGrid_AutoGeneratingColumn(object sender, AutoGeneratingColumnArgs e)
        {
          
                e.Column.HeaderText = "AutoGenerated";
                e.Column.HeaderStyle.BackColor = Color.LightSkyBlue;
            
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

      

       
    }
}
